spring:
  data:
    mongodb:
      host: localhost
      database: cabApplicationV1
      port: 27017
  application:
    name: Cab-info-service   
    
logging:
  level:
    '[org.springframework.data.mongodb]' : debug
    
server:
  port: 8081
  